name: string_literal_finder
description: |
  Find non translated strings: Searches all dart files for string literals, excluding non
  translatable strings. Useful for i18n/l10n.
version: 1.5.0+1
homepage: https://github.com/hpoul/string_literal_finder/tree/master/packages/string_literal_finder

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  analyzer: ">=8.0.0 <11.0.0"
  logging: ">=1.0.0 <2.0.0"
  logging_appenders: ">=1.0.0 <3.0.0"
  path: ">=1.8.0 <2.0.0"
  source_gen: ">=3.0.0-dev <5.0.0"
  string_literal_finder_annotations: ^1.0.0
  args: ">=2.0.0 <3.0.0"
  analyzer_plugin: ">=0.7.0 <0.15.0"
  glob: ">=2.0.0 <3.0.0"
  yaml: ">=3.1.0 <4.0.0"
  recase: ">=4.0.0 <5.0.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.1

executables:
  string_literal_finder:

